
NODE_COUNT = 1

Vagrant.configure("2") do |config|
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "bento/ubuntu-18.04"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.network :private_network, ip: "192.168.56.2"
    jenkins.vm.network "forwarded_port", guest: 8080, host: 8080
    jenkins.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "playbook.yml"
    end
  end
  
  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = "nfqlt/docker"
      subconfig.ssh.username = "project"
      subconfig.ssh.forward_x11 = true
      subconfig.ssh.shell = "bash"
      subconfig.vm.hostname = "node#{i}"
      subconfig.vm.network :private_network, ip: "192.168.56.#{i + 10}"
    end
  end

  # Install avahi on all machines for service discovery. 
  # also install docker and git
  config.vm.provision "shell", inline: <<-SHELL
    apt-get install -y avahi-daemon libnss-mdns
  SHELL
end